spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/loveta
    username: root
    password: root
    hikari:
      max-lifetime: 300000

aliyun:
  oss:
    bucket: loveta-dev

logging:
  level:
    com.github.lingkai5wu.loveta: debug