spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.124.100/loveta
    username: root
    password: 123
  data:
    redis:
      host: 192.168.124.100
      password: 123

logging:
  level:
    com.github.lingkai5wu.loveta: debug