spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loveta
    username: root
    password: root

logging:
  level:
    com.github.lingkai5wu.loveta: debug