spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.124.100/love-ta
    username: root
    password: 123
  data:
    redis:
      host: 192.168.124.100
      password: 123